import { vi } from "vitest";
import { createRef } from "react";
import type { WizardState } from "./useWizardState";

/**
 * Creates a mock WizardState with sensible defaults.
 * Override any field by passing partial overrides.
 */
export function makeWizardState(overrides: Partial<WizardState> = {}): WizardState {
  return {
    step: "welcome",
    setWizardStep: vi.fn(),
    isFetchMode: false,

    host: "",
    setHost: vi.fn(),
    port: "22",
    setPort: vi.fn(),
    sshUser: "root",
    setSshUser: vi.fn(),
    sshPassword: "",
    setSshPassword: vi.fn(),
    sshKeyPath: "",
    setSshKeyPath: vi.fn(),
    showSshPassword: false,
    setShowSshPassword: vi.fn(),

    listenAddress: "0.0.0.0:443",
    setListenAddress: vi.fn(),
    vpnUsername: "",
    setVpnUsername: vi.fn(),
    vpnPassword: "",
    setVpnPassword: vi.fn(),
    showVpnPassword: false,
    setShowVpnPassword: vi.fn(),
    certType: "letsencrypt",
    setCertType: vi.fn(),
    domain: "",
    setDomain: vi.fn(),
    email: "",
    setEmail: vi.fn(),
    certChainPath: "",
    setCertChainPath: vi.fn(),
    certKeyPath: "",
    setCertKeyPath: vi.fn(),
    showAdvanced: false,
    setShowAdvanced: vi.fn(),
    pingEnable: false,
    setPingEnable: vi.fn(),
    speedtestEnable: false,
    setSpeedtestEnable: vi.fn(),
    ipv6Available: true,
    setIpv6Available: vi.fn(),

    serverInfo: null,
    checkError: "",
    confirmUninstall: false,
    setConfirmUninstall: vi.fn(),

    newUsername: "",
    setNewUsername: vi.fn(),
    newPassword: "",
    setNewPassword: vi.fn(),
    showNewPassword: false,
    setShowNewPassword: vi.fn(),
    addingUser: false,
    deletingUser: null,
    confirmDeleteUser: null,
    setConfirmDeleteUser: vi.fn(),
    selectedUser: null,
    setSelectedUser: vi.fn(),
    cameFromFound: false,
    setCameFromFound: vi.fn(),

    deploySteps: {},
    deployLogs: [],
    showLogs: false,
    setShowLogs: vi.fn(),
    errorMessage: "",
    configPath: "",
    copied: false,
    logsEndRef: createRef<HTMLDivElement>(),

    fetchRetryCount: 0,
    setFetchRetryCount: vi.fn(),
    savingConfigFor: null,

    canGoToEndpoint: false,
    isValidEmail: false,
    canDeploy: false,

    handleCheckServer: vi.fn(),
    cancelCheck: vi.fn(),
    handleUninstall: vi.fn(),
    handleCancelDeploy: vi.fn(),
    cancellingDeploy: false,
    handleDeploy: vi.fn(),
    handleSkip: vi.fn(),
    handleFetchConfig: vi.fn(),
    handleSaveConfigDirect: vi.fn(),
    handleAddUser: vi.fn(),
    handleDeleteUser: vi.fn(),
    handleSaveAs: vi.fn(),
    copyLogsToClipboard: vi.fn(),
    saveField: vi.fn(),
    onSetupComplete: vi.fn(),
    ...overrides,
  } as WizardState;
}
