use super::super::*;
use super::super::sanitize::validate_tls_domain;
use russh::client;
use serde::Serialize;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::Duration;

/// UAT 2026-05-20 — cancel checkpoint for MTProto install.
///
/// Returns `Err("MTPROTO_INSTALL_CANCELLED")` if the cancel flag is set.
/// Called between each `exec_command` step in `mtproto_install` so the user's
/// «Отменить» click during install reacts as soon as the current ssh command
/// returns (typical latency: ≤ duration of one step like `apt-get install`).
#[inline]
fn check_cancel(flag: &AtomicBool) -> Result<(), String> {
    if flag.load(Ordering::SeqCst) {
        Err("MTPROTO_INSTALL_CANCELLED".into())
    } else {
        Ok(())
    }
}

// ═══════════════════════════════════════════════════════════════
//   Data structures (mirrored on TS side)
// ═══════════════════════════════════════════════════════════════

#[derive(Clone, Serialize)]
pub struct MtProtoStatus {
    pub installed: bool,
    pub active: bool,
    pub port: u16,
    pub secret: String,
    pub proxy_link: String,
}

#[derive(Clone, Serialize)]
pub struct MtProtoInstallStep {
    pub step: String,   // "download" | "configure" | "generate_secret" | "start_service" | "complete"
    pub status: String, // "running" | "done" | "error"
    pub message: String,
}

// ═══════════════════════════════════════════════════════════════
//   Helpers
// ═══════════════════════════════════════════════════════════════

fn emit_mtproto_step(app: &tauri::AppHandle, step: &str, status: &str, msg: &str) {
    use tauri::Emitter;
    app.emit(
        "mtproto-install-step",
        MtProtoInstallStep {
            step: step.into(),
            status: status.into(),
            message: msg.into(),
        },
    )
    .ok();
}

/// Parse MTProxy environment file to extract secret and port.
/// Format: KEY=VALUE lines (SECRET=..., PORT=..., TAG=...)
fn parse_mtproxy_env(raw: &str) -> (String, u16) {
    let mut secret = String::new();
    let mut port: u16 = 0;
    for line in raw.lines() {
        let line = line.trim();
        if let Some(val) = line.strip_prefix("SECRET=") {
            secret = val.trim().to_string();
        }
        if let Some(val) = line.strip_prefix("PORT=") {
            port = val.trim().parse().unwrap_or(0);
        }
    }
    (secret, port)
}

/// Build tg:// proxy link with dd prefix for random padding (anti-DPI).
fn build_proxy_link(host: &str, port: u16, secret: &str) -> String {
    format!("tg://proxy?server={host}&port={port}&secret=dd{secret}")
}

/// Validate hex secret format (32 hex chars = 16 bytes).
fn is_valid_hex_secret(s: &str) -> bool {
    s.len() == 32 && s.chars().all(|c| c.is_ascii_hexdigit())
}

// ═══════════════════════════════════════════════════════════════
//   Pure helpers (testable без AppHandle / SSH session)
//
//   Phase 17.1 foundation — Wave 2 (mtproto_install / mtproto_uninstall /
//   mtproto_get_status rewrites) будет вызывать эти helpers из async-обёрток.
//   Все функции pure: no I/O, no global state, deterministic output → string.
//
//   Per researcher §Code Examples 1-5 + D-1.9 (admin API primary) +
//   D-2.1/2/3/5/7 (TOML config) + D-4.1 (legacy detection) +
//   Pitfall 1 (links show) + Pitfall 4 (Restart=on-failure).
// ═══════════════════════════════════════════════════════════════

/// Phase 17.1 — render `/etc/telemt/telemt.toml` content.
///
/// PRECONDITION: caller MUST validate inputs:
///  - `secret` via `is_valid_hex_secret` (32-hex chars)
///  - `tls_domain` via `super::super::sanitize::validate_tls_domain`
///  - `port` in 1024..=65535 range
///
/// Output is canonical telemt 3.4.x config:
///  - TLS-camouflage mode (`[general.modes] tls = true`)
///  - `use_middle_proxy = false` (personal proxy, no MTProto cluster)
///  - `[general.links] show = "*"` (Pitfall 1 — required для journalctl fallback)
///  - `[server.api] enabled = true` + listen 127.0.0.1:9091 + whitelist 127.0.0.1/32
///    (D-1.9 primary parse path для proxy_link)
///  - `[censorship] tls_domain` + `mask = true` (TLS handshake mimicry)
///  - `[access.users] trusttunnel = "<secret>"` (single user)
#[allow(dead_code)] // Wave 2 (mtproto_install rewrite) — foundation для Phase 17.1.
fn render_telemt_toml(port: u16, secret: &str, tls_domain: &str) -> String {
    format!(
        "# Telemt MTProto Proxy configuration\n\
# Generated by TrustTunnel Phase 17.1 ({version})\n\
[general]\n\
use_middle_proxy = false\n\
\n\
[general.modes]\n\
classic = false\n\
secure = false\n\
tls = true\n\
\n\
[general.links]\n\
show = \"*\"\n\
\n\
[server]\n\
port = {port}\n\
\n\
[server.api]\n\
enabled = true\n\
listen = \"127.0.0.1:9091\"\n\
whitelist = [\"127.0.0.1/32\"]\n\
\n\
[censorship]\n\
tls_domain = \"{tls_domain}\"\n\
mask = true\n\
\n\
[access.users]\n\
trusttunnel = \"{secret}\"\n\
",
        version = env!("CARGO_PKG_VERSION"),
        port = port,
        tls_domain = tls_domain,
        secret = secret,
    )
}

/// Phase 17.1 — extract existing `port` and `secret` from `/etc/telemt/telemt.toml`
/// for idempotent re-installation (D-3.6).
///
/// Source pattern: Phase 15.1 `parse_vpn_config_known` (server_config.rs:75).
/// Returns `(0, "")` on empty / malformed / missing fields — caller (Wave 2)
/// interprets defaults as «генерировать новый secret + использовать дефолтный порт».
#[allow(dead_code)] // Wave 2 (mtproto_install idempotency check) — foundation.
fn parse_telemt_toml_minimal(raw: &str) -> (u16, String) {
    let doc = match raw.parse::<toml::Value>() {
        Ok(d) => d,
        Err(_) => return (0, String::new()), // soft fail
    };

    let port = doc
        .get("server")
        .and_then(|s| s.get("port"))
        .and_then(|p| p.as_integer())
        .and_then(|n| u16::try_from(n).ok())
        .unwrap_or(0);

    let secret = doc
        .get("access")
        .and_then(|a| a.get("users"))
        .and_then(|u| u.get("trusttunnel"))
        .and_then(|s| s.as_str())
        .unwrap_or("")
        .to_string();

    (port, secret)
}

/// Phase 17.1 — extract `tg://proxy?...` link from telemt admin API JSON response.
///
/// Expected JSON shape per telemt CONFIG_PARAMS docs:
/// ```json
/// {
///   "data": [
///     { "username": "trusttunnel", "links": { "tls": ["tg://proxy?..."] } }
///   ]
/// }
/// ```
///
/// D-1.9 primary path: backend calls `curl -s http://127.0.0.1:9091/v1/users`
/// over SSH and passes raw body здесь. Returns `None` on malformed JSON,
/// missing fields, or empty links array — caller falls back to journalctl.
#[allow(dead_code)] // Wave 2 (mtproto_get_status proxy_link extraction) — foundation.
fn parse_proxy_link_from_api_json(json: &str) -> Option<String> {
    let v: serde_json::Value = serde_json::from_str(json).ok()?;
    let arr = v.get("data")?.as_array()?;
    for user in arr {
        if let Some(links) = user
            .get("links")
            .and_then(|l| l.get("tls"))
            .and_then(|t| t.as_array())
        {
            for link in links {
                if let Some(s) = link.as_str() {
                    if s.starts_with("tg://proxy?") {
                        return Some(s.to_string());
                    }
                }
            }
        }
    }
    None
}

/// Phase 17.1 — extract `tg://proxy?...` link from raw `journalctl -u telemt` output.
///
/// Fallback path (D-1.9) когда admin API недоступен (race на старте сервиса либо ошибка).
/// Reverse-iterate по строкам — picks LATEST link если в логе встречаются несколько
/// (typical при перезапусках сервиса).
///
/// Pure substring search — НЕ требует `regex` crate в runtime (test fixtures only).
/// Sanity check: link must be >20 chars (минимум `tg://proxy?server=&port=&secret=` shell).
#[allow(dead_code)] // Wave 2 (mtproto_get_status journalctl fallback) — foundation.
fn parse_proxy_link_from_journalctl(log_lines: &str) -> Option<String> {
    for line in log_lines.lines().rev() {
        if let Some(start) = line.find("tg://proxy?") {
            let tail = &line[start..];
            // Stop at first whitespace, quote, or end-of-line.
            let end = tail
                .find(|c: char| c.is_whitespace() || c == '"' || c == '\'' || c == '`')
                .unwrap_or(tail.len());
            let link = &tail[..end];
            if link.len() > 20 {
                return Some(link.to_string());
            }
        }
    }
    None
}

/// Phase 17.1 — render `/etc/systemd/system/telemt.service` content (static).
///
/// Verified против telemt QUICK_START_GUIDE.ru.md:191-211 + install.sh:666-686.
/// Differences from install.sh defaults:
///  - `NoNewPrivileges=true` (security hardening beyond install.sh default)
///  - `Restart=on-failure` (NOT `always` — Pitfall 4: иначе `mtproto_stop` триггерит
///    restart loop, и stop никогда не «прилипает»)
///
/// Linux/systemd-only (TrustTunnel поддерживает Ubuntu/Debian; OpenRC variant
/// из install.sh не используем).
#[allow(dead_code)] // Wave 2 (mtproto_install systemd unit creation) — foundation.
fn render_telemt_systemd_unit() -> &'static str {
    "[Unit]
Description=Telemt MTProto Proxy (installed by TrustTunnel)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=telemt
Group=telemt
WorkingDirectory=/opt/telemt
ExecStart=/bin/telemt /etc/telemt/telemt.toml
Restart=on-failure
RestartSec=5
LimitNOFILE=65536
AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_NET_ADMIN
CapabilityBoundingSet=CAP_NET_BIND_SERVICE CAP_NET_ADMIN
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
"
}

/// Phase 17.1 — detect old MTProxy installation via three independent paths.
///
/// Backend (Wave 2) runs ОДНОЙ SSH-командой:
/// ```bash
/// echo "binary=$([ -f /opt/MTProxy/mtproto-proxy ] && echo FOUND || echo NONE)"
/// echo "unit=$([ -f /etc/systemd/system/MTProxy.service ] && echo FOUND || echo NONE)"
/// echo "env=$([ -f /etc/mtproxy.env ] && echo FOUND || echo NONE)"
/// ```
///
/// Helper парсит multi-line stdout — `true` если ЛЮБОЙ из трёх признаков обнаружен
/// (D-4.1 — миграция тихая, любая из 3 улик достаточна для cleanup).
#[allow(dead_code)] // Wave 2 (mtproto_install legacy migration detection) — foundation.
fn detect_legacy_mtproxy_from_outputs(stdout: &str) -> bool {
    stdout.lines().any(|line| {
        let line = line.trim();
        matches!(
            line,
            "binary=FOUND" | "unit=FOUND" | "env=FOUND"
        )
    })
}

/// Phase 17.1 — extract process name from a single `ss -tlnp` output line.
///
/// Typical format:
/// ```
/// LISTEN 0 1024 *:8443 *:*    users:(("nginx",pid=123,fd=5))
/// LISTEN 0 511 0.0.0.0:80 0.0.0.0:* users:(("nginx",pid=456,fd=6),("nginx",pid=457,fd=6))
/// ```
///
/// Returns `Some("nginx")` for both cases. Returns `None` when `users:((` is absent
/// (e.g. process не виден из-за прав, либо socket в TIME_WAIT без owner).
///
/// Used by Wave 2 `mtproto_install` для error message «Порт занят сервисом «{name}»»
/// when port-conflict diagnostic finds non-telemt listener (Phase 17 fix-marathon pattern reuse).
#[allow(dead_code)] // Wave 2 (mtproto_install port-conflict diagnostic) — foundation.
fn extract_process_name_from_ss(line: &str) -> Option<String> {
    let needle = "users:((\"";
    let start = line.find(needle)?;
    let rest = &line[start + needle.len()..];
    let end = rest.find('"')?;
    Some(rest[..end].to_string())
}

// ═══════════════════════════════════════════════════════════════
//   mtproto_get_status — pooled, quick status check (Phase 17.1 telemt)
// ═══════════════════════════════════════════════════════════════
//
// Phase 17.1 rewrite — три источника правды:
//   1. `test -f /bin/telemt` — installed flag
//   2. `systemctl is-active telemt` — active flag
//   3. `cat /etc/telemt/telemt.toml` → parse_telemt_toml_minimal → (port, secret)
//   4. Если active=true — `fetch_proxy_link` (admin API → journalctl fallback)
//
// Phase 17 строил `tg://proxy` link manually через `build_proxy_link(host, port,
// secret)` с `dd`-префиксом. Telemt использует формат `ee{secret}{hex_domain}`
// который мы НЕ строим manually (researcher §Anti-Pattern «Building tg://proxy
// link manually in Rust») — единственный источник правды это сам telemt.
// `host` параметр сохранён в signature (frontend invoke его передаёт), но
// больше не используется в теле — `let _ = host;` подавляет unused_variables.

pub async fn mtproto_get_status(
    app: &tauri::AppHandle,
    handle: &client::Handle<SshHandler>,
    host: &str,
) -> Result<MtProtoStatus, String> {
    let _ = host; // IPC signature compat (Phase 17 строил dd-link через host)
    let sudo = detect_sudo(handle, app).await;

    // ─── Installed check ───────────────────────────────────────
    let (installed_out, _) = exec_command(
        handle,
        app,
        "test -f /bin/telemt && echo INSTALLED || echo NOT_INSTALLED",
    )
    .await?;
    if installed_out.trim().contains("NOT_INSTALLED") {
        return Ok(MtProtoStatus {
            installed: false,
            active: false,
            port: 0,
            secret: String::new(),
            proxy_link: String::new(),
        });
    }

    // ─── Service active check ──────────────────────────────────
    let (svc_out, _) = exec_command(
        handle,
        app,
        &format!("{sudo}systemctl is-active telemt 2>/dev/null || echo inactive"),
    )
    .await?;
    let active = svc_out.trim() == "active";

    // ─── Read telemt.toml для port + secret ────────────────────
    let (toml_out, _) = exec_command(
        handle,
        app,
        &format!("{sudo}cat /etc/telemt/telemt.toml 2>/dev/null || echo ''"),
    )
    .await?;
    let (port, secret) = parse_telemt_toml_minimal(&toml_out);

    // ─── Fetch proxy_link только если активен ──────────────────
    // Если сервис не запущен — admin API недоступен и journalctl может
    // содержать stale ссылку (от прошлого запуска); proxy_link = "" честнее.
    let proxy_link = if active {
        fetch_proxy_link(handle, app, sudo).await
    } else {
        String::new()
    };

    Ok(MtProtoStatus {
        installed: true,
        active,
        port,
        secret,
        proxy_link,
    })
}

// ═══════════════════════════════════════════════════════════════
//   Phase 17.1 — Async install helpers (telemt pipeline)
//
//   Each helper performs ONE step of the 7-step install flow.
//   Helpers are private (module-scope), tested via integration on UAT —
//   pure parsing logic lives in Plan 01 helpers (render_telemt_toml,
//   parse_telemt_toml_minimal, parse_proxy_link_from_*, etc.).
//
//   Cancel checkpoints: каждый helper that issues exec_command is
//   followed in mtproto_install body by `check_cancel(&cancel_flag)?`.
// ═══════════════════════════════════════════════════════════════

/// Phase 17.1 — detect remote architecture (`uname -m`) and libc flavor
/// (`musl` if `ldd --version` mentions musl, else `gnu`).
///
/// Defaults to `("x86_64", "gnu")` if parsing fails — sane fallback for
/// every TrustTunnel-supported Ubuntu/Debian VPS. Per researcher §Pitfall 6
/// we deliberately do NOT detect x86_64-v3 (AVX2+BMI2) — basic x86_64
/// variant works on all hardware, premature optimization for narrow CPU
/// support window не оправдан.
async fn detect_arch_and_libc(
    handle: &client::Handle<SshHandler>,
    app: &tauri::AppHandle,
) -> (String, String) {
    let (uname_out, _) = exec_command(handle, app, "uname -m")
        .await
        .unwrap_or_default();
    let arch = match uname_out.trim() {
        "x86_64" | "amd64" => "x86_64".to_string(),
        "aarch64" | "arm64" => "aarch64".to_string(),
        _ => "x86_64".to_string(), // fallback
    };

    let (libc_out, _) = exec_command(
        handle,
        app,
        "ldd --version 2>&1 | grep -iq musl && echo musl || echo gnu",
    )
    .await
    .unwrap_or_default();
    let libc = match libc_out.trim() {
        "musl" => "musl".to_string(),
        _ => "gnu".to_string(),
    };

    (arch, libc)
}

/// Phase 17.1 — resolve `tls_domain` через hostname-resolution chain.
///
/// Source pattern: `server_config.rs:456-477` (deeplink export Phase 14).
///
/// 1. `grep -oP 'hostname\s*=\s*"\K[^"]+' /opt/trusttunnel/hosts.toml | head -1`
///    → если результат непустой И `!= "trusttunnel.local"` → use as-is.
/// 2. Иначе fallback на `fallback_host` (`params.host` — IP или domain user typed для SSH).
///
/// NO magic default (`petrovich.ru` etc.) — researcher §Open Q5, user confirmed
/// 2026-05-21 per CONTEXT.md D-2.2 option (a): для IP-only установок используем
/// IP-адрес, accepted tradeoff с weak DPI camouflage.
///
/// **S-02 critical:** последняя операция — `validate_tls_domain(&result)?`
/// перед embed в heredoc.
async fn read_trusttunnel_hostname_or_ip(
    handle: &client::Handle<SshHandler>,
    app: &tauri::AppHandle,
    sudo: &str,
    fallback_host: &str,
) -> Result<String, String> {
    let (hostname_raw, _) = exec_command(
        handle,
        app,
        &format!(
            r#"{sudo}grep -oP 'hostname\s*=\s*"\K[^"]+' /opt/trusttunnel/hosts.toml 2>/dev/null | head -1"#
        ),
    )
    .await
    .unwrap_or_default();
    let endpoint_hostname = hostname_raw.trim();

    let resolved = if !endpoint_hostname.is_empty() && endpoint_hostname != "trusttunnel.local" {
        endpoint_hostname.to_string()
    } else {
        fallback_host.trim().to_string()
    };

    // S-02 — char-whitelist validation BEFORE embedding в shell heredoc body.
    validate_tls_domain(&resolved)?;

    Ok(resolved)
}

/// Phase 17.1 — preflight cleanup before fresh install: stop our own zombies
/// (previous telemt process from a crashed install attempt) + wait для port release.
///
/// Modeled on Phase 17 preflight pattern (server_mtproto.rs:179-192 в текущей
/// MTProxy реализации). Errors silenced (`|| true`) — preflight must NEVER
/// abort a fresh install. Best-effort.
async fn telemt_preflight_cleanup(
    handle: &client::Handle<SshHandler>,
    app: &tauri::AppHandle,
    sudo: &str,
    port: u16,
) {
    let cmd = format!(
        "{sudo}systemctl stop telemt 2>/dev/null; \
         {sudo}systemctl disable telemt 2>/dev/null; \
         {sudo}pkill -f /bin/telemt 2>/dev/null; \
         for i in 1 2 3 4 5; do \
           {sudo}ss -tlnp 2>/dev/null | grep -q ':{port} ' || break; \
           sleep 1; \
         done; \
         true"
    );
    exec_command(handle, app, &cmd).await.ok();
}

/// Phase 17.1 — detect legacy MTProxy via three independent paths.
///
/// Runs ONE SSH command with 3 file existence checks (`test -f ...`) → parses
/// multi-line stdout через Plan 01 helper `detect_legacy_mtproxy_from_outputs`.
/// D-4.1 — миграция тихая, ЛЮБАЯ из 3 улик достаточна для cleanup.
async fn detect_legacy_mtproxy(
    handle: &client::Handle<SshHandler>,
    app: &tauri::AppHandle,
    sudo: &str,
) -> bool {
    let cmd = format!(
        r#"{sudo}bash -c 'echo "binary=$(test -f /opt/MTProxy/mtproto-proxy && echo FOUND || echo NONE)"; \
                          echo "unit=$(test -f /etc/systemd/system/MTProxy.service && echo FOUND || echo NONE)"; \
                          echo "env=$(test -f /etc/mtproxy.env && echo FOUND || echo NONE)"'"#
    );
    let (out, _) = exec_command(handle, app, &cmd).await.unwrap_or_default();
    detect_legacy_mtproxy_from_outputs(&out)
}

/// Phase 17.1 — bulk cleanup of legacy MTProxy installation.
///
/// Reads old `PORT=...` from `/etc/mtproxy.env` (for ufw cleanup-by-number),
/// then bulk-stops / disables / removes binaries / unit file / env config.
/// Errors silenced (`|| true`) — best-effort per D-4.4. ufw cleanup via
/// delete-by-number (Phase 17 fix-marathon pattern — `ufw delete allow N/tcp`
/// silently failed для rules with comment metadata).
async fn cleanup_legacy_mtproxy(
    handle: &client::Handle<SshHandler>,
    app: &tauri::AppHandle,
    sudo: &str,
) -> Result<(), String> {
    // 1) Read old port for firewall cleanup.
    let (port_out, _) = exec_command(
        handle,
        app,
        r#"grep -oP 'PORT=\K\d+' /etc/mtproxy.env 2>/dev/null || echo 0"#,
    )
    .await
    .unwrap_or_default();
    let old_port: u16 = port_out.trim().parse().unwrap_or(0);

    // 2) Bulk cleanup (best-effort).
    let cleanup_cmd = format!(
        "{sudo}systemctl stop MTProxy 2>/dev/null; \
         {sudo}systemctl disable MTProxy 2>/dev/null; \
         {sudo}pkill -f /opt/MTProxy/mtproto-proxy 2>/dev/null; \
         {sudo}rm -f /etc/systemd/system/MTProxy.service 2>/dev/null; \
         {sudo}systemctl daemon-reload 2>/dev/null; \
         {sudo}rm -rf /opt/MTProxy 2>/dev/null; \
         {sudo}rm -f /etc/mtproxy.env 2>/dev/null; \
         true"
    );
    exec_command(handle, app, &cleanup_cmd).await.ok();

    // 3) ufw cleanup-by-number если знаем старый порт.
    if old_port > 0 {
        let delim = format!("UFWLEG_EOF_{}", uuid::Uuid::new_v4().simple());
        let ufw_cmd = format!(
            "{sudo}bash <<'{delim}'\n\
NUMBERS=$({sudo}ufw status numbered 2>/dev/null | grep '{port}/tcp' | sed -E 's/^\\[ *([0-9]+)\\].*/\\1/' | sort -rn)\n\
for N in $NUMBERS; do\n\
  yes | {sudo}ufw delete $N >/dev/null 2>&1 || true\n\
done\n\
true\n\
{delim}",
            sudo = sudo,
            delim = delim,
            port = old_port,
        );
        exec_command(handle, app, &ufw_cmd).await.ok();
    }

    Ok(())
}

/// Phase 17.1 — download telemt binary via wget, validate size, extract, install.
///
/// URL pattern: `https://github.com/telemt/telemt/releases/latest/download/telemt-{arch}-linux-{libc}.tar.gz`.
/// Per researcher §Version Pinning — `latest` (no version pin) для security updates +
/// stable URL pattern. SHA256 verify DEFERRED per planner decision (Phase 17.2 polish) —
/// HTTPS-from-github.com baseline trust acceptable.
///
/// Sanity check: tar.gz size > 1 MB (corrupt downloads typically < 100 KB).
async fn download_telemt(
    handle: &client::Handle<SshHandler>,
    app: &tauri::AppHandle,
    sudo: &str,
    arch: &str,
    libc: &str,
) -> Result<(), String> {
    let delim = format!("DL_EOF_{}", uuid::Uuid::new_v4().simple());
    let cmd = format!(
        "{sudo}bash <<'{delim}'\n\
set -e\n\
URL=\"https://github.com/telemt/telemt/releases/latest/download/telemt-{arch}-linux-{libc}.tar.gz\"\n\
wget -q -O /tmp/telemt.tar.gz \"$URL\"\n\
test -s /tmp/telemt.tar.gz\n\
SIZE=$(stat -c%s /tmp/telemt.tar.gz 2>/dev/null || echo 0)\n\
if [ \"$SIZE\" -lt 1000000 ]; then\n\
  echo DOWNLOAD_TOO_SMALL\n\
  exit 1\n\
fi\n\
tar -xzf /tmp/telemt.tar.gz -C /tmp\n\
test -f /tmp/telemt\n\
mv /tmp/telemt /bin/telemt\n\
chmod +x /bin/telemt\n\
rm -f /tmp/telemt.tar.gz\n\
echo DOWNLOAD_OK\n\
{delim}",
        sudo = sudo,
        delim = delim,
        arch = arch,
        libc = libc,
    );
    let (out, _) = exec_command(handle, app, &cmd).await?;
    if !out.contains("DOWNLOAD_OK") {
        return Err("TELEMT_DOWNLOAD_FAILED".into());
    }
    Ok(())
}

/// Phase 17.1 — create `telemt` system user + group, prepare `/etc/telemt`
/// и `/opt/telemt` directories.
///
/// Idempotent — `getent passwd telemt` skip path для re-installs. Per
/// researcher §Pitfall 8: user create MUST precede chown of /etc/telemt,
/// иначе `chown root:telemt` fails with `invalid user`.
async fn create_telemt_user(
    handle: &client::Handle<SshHandler>,
    app: &tauri::AppHandle,
    sudo: &str,
) -> Result<(), String> {
    let cmd = format!(
        "{sudo}bash -c 'getent passwd telemt >/dev/null 2>&1 || useradd -d /opt/telemt -m -r -U telemt; \
         mkdir -p /etc/telemt && mkdir -p /opt/telemt && \
         chown -R telemt:telemt /etc/telemt /opt/telemt && \
         echo USER_OK'"
    );
    let (out, _) = exec_command(handle, app, &cmd).await?;
    if !out.contains("USER_OK") {
        return Err("TELEMT_USER_CREATE_FAILED".into());
    }
    Ok(())
}

/// Phase 17.1 — write `/etc/telemt/telemt.toml` через UUID-randomized heredoc (S-04).
///
/// PRECONDITION (verified at каждом call site по защите в depth):
///  - `secret` — `is_valid_hex_secret(secret) == true`
///  - `tls_domain` — `validate_tls_domain(tls_domain) == Ok(())`
///  - `port` in 1024..=65535
///
/// Двойной heredoc (researcher §Pattern 1): OUTER wraps `bash -c` elevation,
/// INNER wraps TOML body — UUID-randomized delimiter защищает от content-injection
/// даже если TOML body содержит `EOF` substring (defence in depth — render_telemt_toml
/// output никогда не содержит EOF, но invariant preserved).
async fn write_telemt_config(
    handle: &client::Handle<SshHandler>,
    app: &tauri::AppHandle,
    sudo: &str,
    port: u16,
    secret: &str,
    tls_domain: &str,
) -> Result<(), String> {
    let toml_content = render_telemt_toml(port, secret, tls_domain);
    let outer = format!("CFG_OUTER_{}", uuid::Uuid::new_v4().simple());
    let inner = format!("CFG_INNER_{}", uuid::Uuid::new_v4().simple());
    let cmd = format!(
        "{sudo}bash <<'{outer}'\n\
cat > /etc/telemt/telemt.toml <<'{inner}'\n\
{content}\n\
{inner}\n\
chown root:telemt /etc/telemt/telemt.toml\n\
chmod 640 /etc/telemt/telemt.toml\n\
echo CONFIG_OK\n\
{outer}",
        sudo = sudo,
        outer = outer,
        inner = inner,
        content = toml_content,
    );
    let (out, _) = exec_command(handle, app, &cmd).await?;
    if !out.contains("CONFIG_OK") {
        return Err("TELEMT_CONFIG_WRITE_FAILED".into());
    }
    Ok(())
}

/// Phase 17.1 — write `/etc/systemd/system/telemt.service` + daemon-reload + enable.
///
/// Static content из Plan 01 `render_telemt_systemd_unit()` — Restart=on-failure
/// (NOT always — Pitfall 4 trap avoided), User=telemt, NoNewPrivileges=true,
/// CAP_NET_BIND_SERVICE + CAP_NET_ADMIN. UUID heredoc per S-04 invariant
/// (although static content not strictly required — uniformity с config write).
async fn install_telemt_systemd_unit(
    handle: &client::Handle<SshHandler>,
    app: &tauri::AppHandle,
    sudo: &str,
) -> Result<(), String> {
    let unit_content = render_telemt_systemd_unit();
    let outer = format!("UNIT_OUTER_{}", uuid::Uuid::new_v4().simple());
    let inner = format!("UNIT_INNER_{}", uuid::Uuid::new_v4().simple());
    let cmd = format!(
        "{sudo}bash <<'{outer}'\n\
cat > /etc/systemd/system/telemt.service <<'{inner}'\n\
{content}\n\
{inner}\n\
chmod 644 /etc/systemd/system/telemt.service\n\
systemctl daemon-reload\n\
systemctl enable telemt\n\
echo UNIT_OK\n\
{outer}",
        sudo = sudo,
        outer = outer,
        inner = inner,
        content = unit_content,
    );
    let (out, _) = exec_command(handle, app, &cmd).await?;
    if !out.contains("UNIT_OK") {
        return Err("TELEMT_UNIT_INSTALL_FAILED".into());
    }
    Ok(())
}

/// Phase 17.1 — `systemctl start telemt` + retry-loop 6×1s до `is-active`.
///
/// Per researcher §Service Startup Timing — telemt cold start ~200-500ms
/// (Rust+Tokio fast), TLS emulation init (`tls_fetch` HTTPS request) ~1-5s.
/// Typical total: 1-3s, max ~6s. Reuse Phase 17 pattern (6×1s) unchanged.
///
/// Returns `Ok(true)` если service active в 6s window, иначе `Ok(false)`.
async fn start_telemt_and_wait(
    handle: &client::Handle<SshHandler>,
    app: &tauri::AppHandle,
    sudo: &str,
) -> Result<bool, String> {
    exec_command(handle, app, &format!("{sudo}systemctl start telemt")).await?;
    for attempt in 0..6 {
        let (out, _) = exec_command(
            handle,
            app,
            &format!("{sudo}systemctl is-active telemt"),
        )
        .await?;
        if out.trim() == "active" {
            return Ok(true);
        }
        if attempt < 5 {
            tokio::time::sleep(Duration::from_secs(1)).await;
        }
    }
    Ok(false)
}

/// Phase 17.1 — `ufw allow {port}/tcp` (idempotent через ufw native deduplication).
///
/// Best-effort — ufw может отсутствовать (acceptable per researcher §Environment
/// Availability). `|| true` swallows missing-command exit code.
async fn open_telemt_firewall(
    handle: &client::Handle<SshHandler>,
    app: &tauri::AppHandle,
    sudo: &str,
    port: u16,
) -> Result<(), String> {
    let cmd = format!(
        "{sudo}ufw allow {port}/tcp comment 'TrustTunnel MTProto' 2>/dev/null || true; echo FW_OK"
    );
    let (_out, _) = exec_command(handle, app, &cmd).await?;
    Ok(())
}

/// Phase 17.1 — fetch `tg://proxy?...` link via primary API path, fallback journalctl.
///
/// Per researcher §Code Examples 4-5 + D-1.9. PRIMARY: `curl 127.0.0.1:9091/v1/users`
/// + serde JSON parse (Plan 01 `parse_proxy_link_from_api_json`). FALLBACK:
///   `journalctl -u telemt -n 200` + reverse-iterate substring search (Plan 01
///   `parse_proxy_link_from_journalctl`).
///
/// Returns empty string если оба пути fail — caller (mtproto_install) accepts
/// `MtProtoStatus.proxy_link = ""` как degraded state ("installed but no link").
async fn fetch_proxy_link(
    handle: &client::Handle<SshHandler>,
    app: &tauri::AppHandle,
    sudo: &str,
) -> String {
    // Primary: telemt admin API.
    let (api_out, _) = exec_command(
        handle,
        app,
        &format!("{sudo}curl -fsS -m 10 http://127.0.0.1:9091/v1/users 2>/dev/null"),
    )
    .await
    .unwrap_or_default();
    if let Some(link) = parse_proxy_link_from_api_json(&api_out) {
        return link;
    }

    // Fallback: journalctl.
    let (log_out, _) = exec_command(
        handle,
        app,
        &format!("{sudo}journalctl -u telemt -n 200 --no-pager -o cat 2>/dev/null"),
    )
    .await
    .unwrap_or_default();
    parse_proxy_link_from_journalctl(&log_out).unwrap_or_default()
}

/// Phase 17.1 — full rollback on cancel path (D-3.4).
///
/// Best-effort cleanup (errors silenced):
/// - stop + disable telemt service
/// - remove systemd unit file + daemon-reload
/// - remove `/bin/telemt` binary
/// - remove `/etc/telemt` + `/opt/telemt` directories
/// - remove `telemt` system user (`userdel -r` removes home dir)
/// - if `port_opt` provided — ufw delete-by-number for that port
///
/// Called ONLY when `install_inner_result == Err("MTPROTO_INSTALL_CANCELLED")`.
/// NOT called для TELEMT_DOWNLOAD_FAILED / TELEMT_START_FAILED — partial state
/// preserved for idempotent retry (researcher §Open Q5, MTPROTO-07 pattern).
async fn rollback_telemt_install(
    handle: &client::Handle<SshHandler>,
    app: &tauri::AppHandle,
    sudo: &str,
    port_opt: Option<u16>,
) -> Result<(), String> {
    let cleanup_cmd = format!(
        "{sudo}systemctl stop telemt 2>/dev/null || true; \
         {sudo}systemctl disable telemt 2>/dev/null || true; \
         {sudo}rm -f /etc/systemd/system/telemt.service 2>/dev/null; \
         {sudo}systemctl daemon-reload 2>/dev/null; \
         {sudo}rm -f /bin/telemt 2>/dev/null; \
         {sudo}rm -rf /etc/telemt /opt/telemt 2>/dev/null; \
         {sudo}userdel -r telemt 2>/dev/null || true; \
         true"
    );
    exec_command(handle, app, &cleanup_cmd).await.ok();

    if let Some(port) = port_opt {
        let delim = format!("UFWRB_EOF_{}", uuid::Uuid::new_v4().simple());
        let ufw_cmd = format!(
            "{sudo}bash <<'{delim}'\n\
NUMBERS=$({sudo}ufw status numbered 2>/dev/null | grep '{port}/tcp' | sed -E 's/^\\[ *([0-9]+)\\].*/\\1/' | sort -rn)\n\
for N in $NUMBERS; do\n\
  yes | {sudo}ufw delete $N >/dev/null 2>&1 || true\n\
done\n\
true\n\
{delim}",
            sudo = sudo,
            delim = delim,
            port = port,
        );
        exec_command(handle, app, &ufw_cmd).await.ok();
    }

    Ok(())
}

// ═══════════════════════════════════════════════════════════════
//   mtproto_install — direct connect, long-running (Phase 17.1 rewrite)
//   Pipeline: cleanup_legacy → download_binary → create_user →
//             configure_telemt → start_service → open_firewall → complete
//   Uses telemt 3.4.x (Rust + Tokio + TLS-camouflage mode).
// ═══════════════════════════════════════════════════════════════

pub async fn mtproto_install(
    app: &tauri::AppHandle,
    params: SshParams,
    mtproto_port: u16,
    cancel_flag: Arc<AtomicBool>,
) -> Result<MtProtoStatus, String> {
    // ── 1. Early port validation (S-02 surface defence) ──
    if mtproto_port < 1024 {
        return Err(format!("MTPROTO_INVALID_PORT|{mtproto_port}"));
    }
    let port = mtproto_port;

    let handle = params.connect_with_app(app.clone()).await?;
    let sudo = detect_sudo(&handle, app).await;
    check_cancel(&cancel_flag)?;

    let host_for_link = params.host.clone();
    let install_started_port = port;

    // ── Async block для всей pipeline — ловит errors в `install_inner_result`,
    //    позволяет rollback path после блока. ──
    let install_inner_result: Result<MtProtoStatus, String> = async {
        // ─── STEP 0: cleanup_legacy ───────────────────────────────
        emit_mtproto_step(app, "cleanup_legacy", "running", "");
        let has_legacy = detect_legacy_mtproxy(&handle, app, sudo).await;
        if has_legacy {
            cleanup_legacy_mtproxy(&handle, app, sudo).await.ok();
            emit_mtproto_step(
                app,
                "cleanup_legacy",
                "done",
                "Старый MTProxy был обнаружен и удалён в процессе установки",
            );
        } else {
            emit_mtproto_step(app, "cleanup_legacy", "done", "");
        }
        check_cancel(&cancel_flag)?;

        // ─── Preflight cleanup (silent — own zombies) ─────────────
        telemt_preflight_cleanup(&handle, app, sudo, port).await;
        check_cancel(&cancel_flag)?;

        // ─── Port conflict check (after own preflight) ────────────
        let (busy_out, _) = exec_command(
            &handle,
            app,
            &format!(
                "{sudo}ss -tlnp 2>/dev/null | awk -v port=:{port} '$0 ~ port {{print $0}}' | head -1"
            ),
        )
        .await?;
        if !busy_out.trim().is_empty() {
            // Parse process name from `ss` output (Phase 17 fix-marathon pattern).
            let proc_name = extract_process_name_from_ss(&busy_out)
                .unwrap_or_else(|| "(неизвестный)".to_string());
            emit_mtproto_step(
                app,
                "start_service",
                "error",
                &format!("Порт {port} занят сервисом «{proc_name}»"),
            );
            return Err(format!("MTPROTO_PORT_BUSY|{port}|{proc_name}"));
        }

        // ─── STEP 1: download_binary ──────────────────────────────
        emit_mtproto_step(app, "download_binary", "running", "");
        let (arch, libc) = detect_arch_and_libc(&handle, app).await;
        if let Err(e) = download_telemt(&handle, app, sudo, &arch, &libc).await {
            emit_mtproto_step(app, "download_binary", "error", "Не удалось скачать telemt");
            return Err(e);
        }
        emit_mtproto_step(app, "download_binary", "done", "");
        check_cancel(&cancel_flag)?;

        // ─── STEP 2: create_user ──────────────────────────────────
        emit_mtproto_step(app, "create_user", "running", "");
        if let Err(e) = create_telemt_user(&handle, app, sudo).await {
            emit_mtproto_step(
                app,
                "create_user",
                "error",
                "Не удалось создать пользователя telemt",
            );
            return Err(e);
        }
        emit_mtproto_step(app, "create_user", "done", "");
        check_cancel(&cancel_flag)?;

        // ─── STEP 3: configure_telemt ─────────────────────────────
        emit_mtproto_step(app, "configure_telemt", "running", "");

        // Resolve tls_domain (read_trusttunnel_hostname_or_ip uses validate_tls_domain).
        let tls_domain =
            read_trusttunnel_hostname_or_ip(&handle, app, sudo, &host_for_link).await?;

        // Secret: reuse existing valid (D-3.6 idempotency / MTPROTO-07 pattern) либо generate new.
        let (existing_toml, _) = exec_command(
            &handle,
            app,
            &format!("{sudo}cat /etc/telemt/telemt.toml 2>/dev/null || echo ''"),
        )
        .await?;
        let (_existing_port, existing_secret) = parse_telemt_toml_minimal(&existing_toml);
        let secret = if is_valid_hex_secret(&existing_secret) {
            existing_secret
        } else {
            let (gen_out, _) = exec_command(&handle, app, "openssl rand -hex 16").await?;
            let gen = gen_out.trim().to_string();
            if !is_valid_hex_secret(&gen) {
                emit_mtproto_step(
                    app,
                    "configure_telemt",
                    "error",
                    "Не удалось сгенерировать корректный secret",
                );
                return Err("TELEMT_SECRET_INVALID".into());
            }
            gen
        };

        // Defensive re-check (Phase 17 paranoia preserved) — secret may come from
        // user-edited file, validate immediately before embedding в shell heredoc.
        if !is_valid_hex_secret(&secret) {
            return Err("TELEMT_SECRET_INVALID".into());
        }

        if let Err(e) =
            write_telemt_config(&handle, app, sudo, port, &secret, &tls_domain).await
        {
            emit_mtproto_step(
                app,
                "configure_telemt",
                "error",
                "Не удалось записать telemt.toml",
            );
            return Err(e);
        }
        emit_mtproto_step(app, "configure_telemt", "done", "");
        check_cancel(&cancel_flag)?;

        // ─── STEP 4: start_service ────────────────────────────────
        emit_mtproto_step(app, "start_service", "running", "");
        if let Err(e) = install_telemt_systemd_unit(&handle, app, sudo).await {
            emit_mtproto_step(app, "start_service", "error", "Не удалось установить systemd unit");
            return Err(e);
        }
        let active = start_telemt_and_wait(&handle, app, sudo).await?;
        if !active {
            emit_mtproto_step(
                app,
                "start_service",
                "error",
                "Сервис не вышел в состояние active за 6 секунд",
            );
            return Err("TELEMT_START_FAILED".into());
        }
        emit_mtproto_step(app, "start_service", "done", "");
        check_cancel(&cancel_flag)?;

        // ─── STEP 5: open_firewall ────────────────────────────────
        emit_mtproto_step(app, "open_firewall", "running", "");
        open_telemt_firewall(&handle, app, sudo, port).await.ok();
        emit_mtproto_step(app, "open_firewall", "done", "");
        check_cancel(&cancel_flag)?;

        // ─── STEP 6: complete (fetch proxy_link) ──────────────────
        //
        // Retry: telemt admin API может не быть ready immediately after
        // systemctl start (TLS emulation init still completing). 3×500ms =
        // max 1.5s extra wait — достаточно для TLS init без блокировки UI.
        // Per Plan-check advisory #7 — progressive retry instead of single sleep.
        let mut proxy_link = String::new();
        for attempt in 0..3 {
            if attempt > 0 {
                tokio::time::sleep(Duration::from_millis(500)).await;
            }
            proxy_link = fetch_proxy_link(&handle, app, sudo).await;
            if !proxy_link.is_empty() {
                break;
            }
        }
        // Если link всё ещё пуст после 3 retries — caller получит
        // proxy_link = "", UI отрендерит «installed but link не извлечена»
        // (acceptable degradation per researcher §Open Q5).
        emit_mtproto_step(app, "complete", "done", "");

        Ok(MtProtoStatus {
            installed: true,
            active: true,
            port,
            secret,     // D-29: returns в Tauri response, но НЕ через emit_log/emit_mtproto_step
            proxy_link, // D-29: returns в response, но НЕ через emit_log/emit_mtproto_step
        })
    }
    .await;

    // ─── Cancel/error rollback ────────────────────────────────────
    //
    // ASYMMETRY by design (per Plan-check advisory #6 — accepted tradeoff):
    //
    // - `MTPROTO_INSTALL_CANCELLED` → FULL rollback (D-3.4 «прервать и откатить»).
    //   User explicitly clicked Cancel → expects clean server state.
    //
    // - `TELEMT_DOWNLOAD_FAILED` / `TELEMT_START_FAILED` / `MTPROTO_PORT_BUSY` /
    //   other errors → NO rollback. Partial state remains on server.
    //
    // Why no rollback on non-cancel errors:
    //   1. Idempotent retry — next `mtproto_install` detects partial state
    //      (existing `telemt.toml` with valid secret, existing user, existing
    //      unit), reuses secret через `parse_telemt_toml_minimal` (D-3.6
    //      idempotency / MTPROTO-07 pattern), and re-runs all steps без поломки.
    //   2. User может want диагностировать (e.g. `journalctl -u telemt` после
    //      `TELEMT_START_FAILED`) — rollback бы стёр evidence.
    //   3. Researcher §Open Q5 explicit recommendation: silent restart accepted.
    //
    // If user wants clean state — they click «Удалить» (`mtproto_uninstall` —
    // surgical cleanup per D-3.7, Plan 04 переписывает под telemt).
    if let Err(ref err) = install_inner_result {
        if err == "MTPROTO_INSTALL_CANCELLED" {
            rollback_telemt_install(&handle, app, sudo, Some(install_started_port))
                .await
                .ok();
        }
    }

    install_inner_result
}

// ═══════════════════════════════════════════════════════════════
//   mtproto_start / mtproto_stop — pooled, quick state toggles
// ═══════════════════════════════════════════════════════════════
//
// UAT 2026-05-21 — user sees status «Установлен, не запущен» after
// install (or after a reboot / crash-loop give-up by systemd). Without
// a Start button in the modal there's no recovery path — they'd have
// to ssh in and run `systemctl start telemt` by hand. These two verbs
// expose the toggle. Both pull a fresh MtProtoStatus on return so the
// caller can immediately re-render (no extra get_status round-trip).
//
// Phase 17.1 — logic 1:1 Phase 17, только unit name `MTProxy` → `telemt`.
// `Restart=on-failure` (render_telemt_systemd_unit per Plan 01) гарантирует
// что `systemctl stop` НЕ триггерит auto-restart loop (Pitfall 4 mitigation).

pub async fn mtproto_start(
    app: &tauri::AppHandle,
    handle: &client::Handle<SshHandler>,
    host: &str,
) -> Result<MtProtoStatus, String> {
    let sudo = detect_sudo(handle, app).await;
    // `systemctl start` is fire-and-forget; service may take a beat to
    // bind its port and complete TLS init. Same 6×1s retry pattern as
    // install — accommodates Ubuntu 24.04's «activating» → «active»
    // window without flagging a false START_FAILED for a service that's
    // actually about to come up.
    exec_command(handle, app, &format!("{sudo}systemctl start telemt")).await?;
    for attempt in 0..6 {
        let (out, _) = exec_command(
            handle,
            app,
            &format!("{sudo}systemctl is-active telemt"),
        )
        .await?;
        if out.trim() == "active" {
            break;
        }
        if attempt < 5 {
            tokio::time::sleep(std::time::Duration::from_secs(1)).await;
        }
    }
    // Re-read full status (port + secret + proxy_link).
    mtproto_get_status(app, handle, host).await
}

pub async fn mtproto_stop(
    app: &tauri::AppHandle,
    handle: &client::Handle<SshHandler>,
    host: &str,
) -> Result<MtProtoStatus, String> {
    let sudo = detect_sudo(handle, app).await;
    exec_command(
        handle,
        app,
        &format!("{sudo}systemctl stop telemt 2>/dev/null; echo STOP_OK"),
    )
    .await?;
    mtproto_get_status(app, handle, host).await
}

// ═══════════════════════════════════════════════════════════════
//   mtproto_uninstall — direct connect
// ═══════════════════════════════════════════════════════════════

pub async fn mtproto_uninstall(
    app: &tauri::AppHandle,
    params: SshParams,
) -> Result<(), String> {
    let handle = params.connect_with_app(app.clone()).await?;
    let sudo = detect_sudo(&handle, app).await;

    // Read env config to get port for firewall cleanup
    let (cfg_out, _) = exec_command(
        &handle,
        app,
        "cat /etc/mtproxy.env 2>/dev/null || echo ''",
    )
    .await?;
    let (_, port) = parse_mtproxy_env(&cfg_out);

    // Stop and disable service
    exec_command(
        &handle,
        app,
        &format!("{sudo}systemctl stop MTProxy 2>/dev/null; {sudo}systemctl disable MTProxy 2>/dev/null; echo STOP_OK"),
    )
    .await?;

    // Remove systemd unit
    exec_command(
        &handle,
        app,
        &format!("{sudo}rm -f /etc/systemd/system/MTProxy.service && {sudo}systemctl daemon-reload"),
    )
    .await?;

    // Remove MTProxy directory (source + binary)
    exec_command(&handle, app, &format!("{sudo}rm -rf /opt/MTProxy")).await?;

    // Remove env config
    exec_command(&handle, app, &format!("{sudo}rm -f /etc/mtproxy.env")).await?;

    // Close firewall port.
    //
    // UAT 2026-05-20 — switched from `ufw delete allow {port}/tcp` to
    // delete-by-number because the spec form silently fails when the rule
    // carries comment metadata (`ufw allow {port}/tcp comment 'MTProto'`
    // is what install adds). Symptom: user uninstalls, reopens Брандмауэр
    // modal, MTProto rule is still there.
    //
    // Approach:
    //   1) Enumerate every rule whose `to` column matches `{port}/tcp` via
    //      `ufw status numbered` (matches IPv4 + IPv6 pair, and rules with
    //      `comment '...'` since grep doesn't care about trailing fields).
    //   2) Sort numbers DESCENDING — deleting a rule renumbers everything
    //      below it, so we work from the bottom up to keep indices stable.
    //   3) `yes | ufw delete N` to bypass the interactive confirm prompt.
    //   4) Belt-and-suspenders: also try `ufw delete allow {port}/tcp` as a
    //      no-op fallback (covers edge cases where status output format
    //      drifts between distros).
    //
    // `<<'UFWEOF'` (single-quoted heredoc terminator) prevents the OUTER
    // shell from expanding $NUMBERS / $N — those get expanded by the bash
    // instance that receives the heredoc body via stdin, at execution time.
    if port > 0 {
        exec_command(
            &handle,
            app,
            &format!(
                "{sudo}bash <<'UFWEOF'\n\
NUMBERS=$({sudo}ufw status numbered 2>/dev/null | grep '{port}/tcp' | sed -E 's/^\\[ *([0-9]+)\\].*/\\1/' | sort -rn)\n\
for N in $NUMBERS; do\n\
  yes | {sudo}ufw delete $N >/dev/null 2>&1 || true\n\
done\n\
{sudo}ufw delete allow {port}/tcp >/dev/null 2>&1 || true\n\
echo FW_OK\n\
UFWEOF\n"
            ),
        )
        .await?;
    }

    Ok(())
}

// ═══════════════════════════════════════════════════════════════
//   Tests for pure helpers (no SSH / no AppHandle required)
// ═══════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    // ─── render_telemt_toml ───────────────────────────────────

    #[test]
    fn renders_valid_toml() {
        let out = render_telemt_toml(
            8443,
            "0123456789abcdef0123456789abcdef",
            "trusttunnel.example.com",
        );
        // Result must parse as valid TOML
        let parsed: toml::Value = toml::from_str(&out).expect("must parse");
        assert_eq!(parsed["server"]["port"].as_integer(), Some(8443));
        assert_eq!(
            parsed["censorship"]["tls_domain"].as_str(),
            Some("trusttunnel.example.com")
        );
        assert_eq!(parsed["general"]["modes"]["tls"].as_bool(), Some(true));
        assert_eq!(
            parsed["access"]["users"]["trusttunnel"].as_str(),
            Some("0123456789abcdef0123456789abcdef")
        );
    }

    #[test]
    fn renders_links_show() {
        // Pitfall 1 — `[general.links] show = "*"` required для journalctl fallback.
        let out = render_telemt_toml(8443, &"0".repeat(32), "x.com");
        assert!(out.contains("[general.links]"));
        assert!(out.contains("show = \"*\""));
    }

    #[test]
    fn renders_server_api_enabled() {
        // D-1.9 — primary parse path для proxy_link (localhost-only admin API).
        let out = render_telemt_toml(8443, &"a".repeat(32), "x.com");
        let parsed: toml::Value = toml::from_str(&out).expect("must parse");
        assert_eq!(parsed["server"]["api"]["enabled"].as_bool(), Some(true));
        assert_eq!(
            parsed["server"]["api"]["listen"].as_str(),
            Some("127.0.0.1:9091")
        );
        let whitelist = parsed["server"]["api"]["whitelist"]
            .as_array()
            .expect("whitelist must be an array");
        assert_eq!(whitelist.len(), 1);
        assert_eq!(whitelist[0].as_str(), Some("127.0.0.1/32"));
    }

    #[test]
    fn renders_use_middle_proxy_false() {
        // CONTEXT.md scope §Не входит — personal proxy, no MTProto cluster.
        let out = render_telemt_toml(8443, &"a".repeat(32), "x.com");
        let parsed: toml::Value = toml::from_str(&out).expect("must parse");
        assert_eq!(
            parsed["general"]["use_middle_proxy"].as_bool(),
            Some(false)
        );
    }

    #[test]
    fn renders_tls_mode_enabled() {
        // D-2.1 — все три mode flags явно проставлены.
        let out = render_telemt_toml(8443, &"a".repeat(32), "x.com");
        let parsed: toml::Value = toml::from_str(&out).expect("must parse");
        let modes = &parsed["general"]["modes"];
        assert_eq!(modes["classic"].as_bool(), Some(false));
        assert_eq!(modes["secure"].as_bool(), Some(false));
        assert_eq!(modes["tls"].as_bool(), Some(true));
    }

    // ─── parse_telemt_toml_minimal ────────────────────────────

    #[test]
    fn parses_existing_telemt_toml() {
        let raw = r#"
[server]
port = 8443

[access.users]
trusttunnel = "0123456789abcdef0123456789abcdef"
"#;
        let (port, secret) = parse_telemt_toml_minimal(raw);
        assert_eq!(port, 8443);
        assert_eq!(secret, "0123456789abcdef0123456789abcdef");
    }

    #[test]
    fn returns_defaults_on_empty() {
        let (port, secret) = parse_telemt_toml_minimal("");
        assert_eq!(port, 0);
        assert_eq!(secret, "");
    }

    #[test]
    fn returns_defaults_on_malformed() {
        let (port, secret) = parse_telemt_toml_minimal("not [valid toml");
        assert_eq!(port, 0);
        assert_eq!(secret, "");
    }

    #[test]
    fn returns_zero_when_port_missing() {
        let raw = r#"
[access.users]
trusttunnel = "0123456789abcdef0123456789abcdef"
"#;
        let (port, secret) = parse_telemt_toml_minimal(raw);
        assert_eq!(port, 0);
        assert_eq!(secret, "0123456789abcdef0123456789abcdef");
    }

    #[test]
    fn returns_empty_secret_when_user_missing() {
        let raw = r#"
[server]
port = 9443
"#;
        let (port, secret) = parse_telemt_toml_minimal(raw);
        assert_eq!(port, 9443);
        assert_eq!(secret, "");
    }

    // ─── parse_proxy_link_from_api_json ───────────────────────

    #[test]
    fn parses_canonical_api_response() {
        let json = r#"{
            "data": [
                { "username": "trusttunnel",
                  "links": { "tls": ["tg://proxy?server=1.2.3.4&port=8443&secret=eeabcd"] } }
            ]
        }"#;
        let link = parse_proxy_link_from_api_json(json).expect("must parse");
        assert!(link.starts_with("tg://proxy?"));
        assert!(link.contains("server=1.2.3.4"));
    }

    #[test]
    fn returns_none_on_malformed_json() {
        assert!(parse_proxy_link_from_api_json("not json").is_none());
    }

    #[test]
    fn returns_none_on_empty_links_array() {
        let json = r#"{"data":[{"links":{"tls":[]}}]}"#;
        assert!(parse_proxy_link_from_api_json(json).is_none());
    }

    // ─── parse_proxy_link_from_journalctl ─────────────────────

    #[test]
    fn extracts_link_from_typical_journal_line() {
        let log = "May 21 10:30:00 host telemt[1234]: Proxy link: tg://proxy?server=1.2.3.4&port=8443&secret=ee0123 (for user 'trusttunnel')\nMay 21 10:30:01 host telemt[1234]: Listening on 0.0.0.0:8443\n";
        let link = parse_proxy_link_from_journalctl(log).expect("must extract");
        assert!(link.starts_with("tg://proxy?"));
        assert_eq!(link, "tg://proxy?server=1.2.3.4&port=8443&secret=ee0123");
    }

    #[test]
    fn returns_none_when_no_link_present() {
        assert!(parse_proxy_link_from_journalctl("normal log line\nno link here").is_none());
    }

    #[test]
    fn picks_latest_link_when_multiple_present() {
        // Reverse-iterate ловит самую свежую (нижнюю) ссылку — typical при перезапусках.
        let log = "old link: tg://proxy?server=1.1.1.1&port=80&secret=eeAAAA\nrestart\nnew link: tg://proxy?server=2.2.2.2&port=8443&secret=eeBBBB";
        let link = parse_proxy_link_from_journalctl(log).expect("must extract");
        assert!(link.contains("server=2.2.2.2"));
    }

    // ─── render_telemt_systemd_unit ───────────────────────────

    #[test]
    fn renders_correct_unit_directives() {
        let unit = render_telemt_systemd_unit();
        // Pitfall 4 — Restart=on-failure (NOT always)
        assert!(unit.contains("Restart=on-failure"));
        assert!(!unit.contains("Restart=always"));
        // Security hardening
        assert!(unit.contains("User=telemt"));
        assert!(unit.contains("Group=telemt"));
        assert!(unit.contains("NoNewPrivileges=true"));
        // Privilege boundary
        assert!(unit.contains("AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_NET_ADMIN"));
        assert!(unit.contains("CapabilityBoundingSet=CAP_NET_BIND_SERVICE CAP_NET_ADMIN"));
        // ExecStart
        assert!(unit.contains("ExecStart=/bin/telemt /etc/telemt/telemt.toml"));
    }

    // ─── detect_legacy_mtproxy_from_outputs ───────────────────

    #[test]
    fn detects_legacy_via_binary() {
        assert!(detect_legacy_mtproxy_from_outputs(
            "binary=FOUND\nunit=NONE\nenv=NONE\n"
        ));
    }

    #[test]
    fn detects_legacy_via_unit() {
        assert!(detect_legacy_mtproxy_from_outputs(
            "binary=NONE\nunit=FOUND\nenv=NONE\n"
        ));
    }

    #[test]
    fn detects_legacy_via_env() {
        assert!(detect_legacy_mtproxy_from_outputs(
            "binary=NONE\nunit=NONE\nenv=FOUND\n"
        ));
    }

    #[test]
    fn returns_false_when_all_absent() {
        assert!(!detect_legacy_mtproxy_from_outputs(
            "binary=NONE\nunit=NONE\nenv=NONE\n"
        ));
    }

    // ─── is_valid_hex_secret (existing, reused) ───────────────

    #[test]
    fn hex_secret_accepts_32_hex_chars() {
        assert!(is_valid_hex_secret("0123456789abcdef0123456789abcdef"));
    }

    #[test]
    fn hex_secret_rejects_short() {
        assert!(!is_valid_hex_secret("abc"));
    }

    #[test]
    fn hex_secret_rejects_non_hex_chars() {
        // Последний символ `Z` — не hex.
        assert!(!is_valid_hex_secret("0123456789abcdef0123456789ABCDEZ"));
    }

    // ─── extract_process_name_from_ss ─────────────────────────

    #[test]
    fn extracts_single_user_process_name() {
        let line = r#"LISTEN 0 1024 *:8443 *:*    users:(("nginx",pid=123,fd=5))"#;
        assert_eq!(extract_process_name_from_ss(line), Some("nginx".into()));
    }

    #[test]
    fn extracts_first_user_when_multiple_workers() {
        let line = r#"LISTEN 0 511 0.0.0.0:80 0.0.0.0:* users:(("nginx",pid=456,fd=6),("nginx",pid=457,fd=6))"#;
        assert_eq!(extract_process_name_from_ss(line), Some("nginx".into()));
    }

    #[test]
    fn returns_none_when_no_users_block() {
        let line = "LISTEN 0 1024 *:8443 *:*";
        assert_eq!(extract_process_name_from_ss(line), None);
    }
}
