name: ❓ Задать вопрос
description: Если непонятно, как что-то работает
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Прежде чем спрашивать, загляните в [описание последнего
        выпуска](https://github.com/ialexbond/TrustTunnelClientForWindows/releases) — там написано,
        что появилось и что изменилось.

  - type: dropdown
    id: edition
    attributes:
      label: Какое издание
      options:
        - Pro
        - Light
        - Вопрос не про конкретное издание
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Вопрос
    validations:
      required: true
