import { type ReactNode } from "react";
import { ToggleField } from "./fields/ToggleField";
import { StringField } from "./fields/StringField";
import { NumberField } from "./fields/NumberField";
import { ArrayOfTablesBlock } from "./fields/ArrayOfTablesBlock";
import { RawUnknownField } from "./fields/RawUnknownField";
import { TabsInline, type TabsInlineTab } from "../../../shared/ui/TabsInline";
import type { TomlFieldSchema } from "./types";

/**
 * Phase 15.1 — Visitor pattern dispatch (REQ-15.7 schema-driven).
 *
 * Switch by `schema.type.kind`:
 *   boolean           → ToggleField
 *   integer           → NumberField
 *   string            → StringField
 *   array-of-strings  → string-array editor (renders as comma-joined Input —
 *                       minimal Phase 15.1 implementation; future: dedicated
 *                       chip-list primitive если defaults map flags array
 *                       with rich semantics)
 *   array-of-tables   → ArrayOfTablesBlock
 *   table:
 *     ≥2 sub-sections → TabsInline (D-9.1 — e.g. [listen_protocols] HTTP/1 | HTTP/2 | QUIC)
 *     1 sub-section   → inline section heading
 *     0 sub-sections  → flat children list под heading
 *   unknown           → RawUnknownField (D-16.1 forward-compat)
 *
 * D-6.1 filter: при showAll=false (default) leaf node where !schema.isExplicit
 * returns null. table/array-of-tables containers НЕ filtered (children
 * dispatched recursively с тем же showAll).
 */
export interface SchemaFieldRendererProps {
  schema: TomlFieldSchema;
  /**
   * D-6.1 filter — when false, default-only fields (isExplicit=false synthesized
   * in Plan 15.1-04 Pass 2) are hidden. Defaults to false при undefined.
   * Plan 15.1-06 ConfigurationTab passes per-file showAll state.
   */
  showAll?: boolean;
  /** Get child schema array для table rendering (ordered list of TomlFieldSchema). */
  getTableChildSchemas?: (parentPath: string[]) => TomlFieldSchema[];
  /** Get array-of-tables entry as nested schemas array. */
  getArrayEntrySchemas?: (parentPath: string[], entryIndex: number) => TomlFieldSchema[];
  /** Validator lookup by path (e.g. listen_address → validateListenAddress). */
  getValidator?: (path: string[]) => ((value: unknown) => string) | undefined;
  onChange: (path: string[], value: unknown) => void;
  onAddArrayEntry?: (path: string[]) => void;
  onRemoveArrayEntry?: (path: string[], index: number) => void;
  disabled?: boolean;
}

export function SchemaFieldRenderer({
  schema,
  showAll,
  getTableChildSchemas,
  getArrayEntrySchemas,
  getValidator,
  onChange,
  onAddArrayEntry,
  onRemoveArrayEntry,
  disabled,
}: SchemaFieldRendererProps): ReactNode {
  // D-6.1: при showAll=false hide default-only synthetic fields (isExplicit=false)
  // generated by Plan 15.1-04 buildFileSchemaTree Pass 2.
  // table/array-of-tables containers НЕ filter'ятся (children dispatched recursively).
  if (
    !showAll &&
    !schema.isExplicit &&
    schema.type.kind !== "table" &&
    schema.type.kind !== "array-of-tables"
  ) {
    return null;
  }

  switch (schema.type.kind) {
    case "boolean":
      return (
        <ToggleField
          schema={schema}
          onChange={(path, value) => onChange(path, value)}
          disabled={disabled}
        />
      );

    case "integer": {
      const validator = getValidator?.(schema.path) as
        | ((v: number) => string)
        | undefined;
      return (
        <NumberField
          schema={schema}
          validator={validator}
          onChange={(path, value) => onChange(path, value)}
          disabled={disabled}
        />
      );
    }

    case "string": {
      const validator = getValidator?.(schema.path) as
        | ((v: string) => string)
        | undefined;
      return (
        <StringField
          schema={schema}
          validator={validator}
          onChange={(path, value) => onChange(path, value)}
          disabled={disabled}
        />
      );
    }

    case "array-of-strings": {
      // Minimal Phase 15.1 implementation: comma-joined Input.
      // Per D-PRE-3 — schema-driven render handles this без curated component.
      const validator = getValidator?.(schema.path) as
        | ((v: string) => string)
        | undefined;
      const csvValue = (schema.type.value as string[]).join(", ");
      const wrappedSchema: TomlFieldSchema = {
        ...schema,
        type: { kind: "string", value: csvValue },
      };
      return (
        <StringField
          schema={wrappedSchema}
          validator={validator}
          onChange={(path, value) => {
            const arr = (value as string)
              .split(",")
              .map((s) => s.trim())
              .filter((s) => s.length > 0);
            onChange(path, arr);
          }}
          disabled={disabled}
        />
      );
    }

    case "array-of-tables":
      if (!onAddArrayEntry || !onRemoveArrayEntry || !getArrayEntrySchemas) return null;
      return (
        <ArrayOfTablesBlock
          schema={schema}
          onAdd={onAddArrayEntry}
          onRemove={onRemoveArrayEntry}
          renderEntry={(idx) => (
            <>
              {getArrayEntrySchemas(schema.path, idx).map((childSchema) => (
                <SchemaFieldRenderer
                  key={childSchema.path.join(".")}
                  schema={childSchema}
                  showAll={showAll}
                  getTableChildSchemas={getTableChildSchemas}
                  getArrayEntrySchemas={getArrayEntrySchemas}
                  getValidator={getValidator}
                  onChange={onChange}
                  onAddArrayEntry={onAddArrayEntry}
                  onRemoveArrayEntry={onRemoveArrayEntry}
                  disabled={disabled}
                />
              ))}
            </>
          )}
          disabled={disabled}
        />
      );

    case "table": {
      if (!getTableChildSchemas) return null;
      const childSchemas = getTableChildSchemas(schema.path);

      // Sub-tables = children where childSchema.type.kind === "table"
      const subTables = childSchemas.filter((c) => c.type.kind === "table");

      // D-9.1 dispatch:
      if (subTables.length >= 2) {
        const tabs: TabsInlineTab[] = subTables.map((sub) => ({
          id: sub.key,
          label: sub.key, // raw English D-3.1
          content: (
            <div className="flex flex-col gap-3 py-3">
              {getTableChildSchemas(sub.path).map((leafSchema) => (
                <SchemaFieldRenderer
                  key={leafSchema.path.join(".")}
                  schema={leafSchema}
                  showAll={showAll}
                  getTableChildSchemas={getTableChildSchemas}
                  getArrayEntrySchemas={getArrayEntrySchemas}
                  getValidator={getValidator}
                  onChange={onChange}
                  onAddArrayEntry={onAddArrayEntry}
                  onRemoveArrayEntry={onRemoveArrayEntry}
                  disabled={disabled}
                />
              ))}
            </div>
          ),
        }));

        // Render scalar leaves (non-table children) above tabs as preamble
        const scalarLeaves = childSchemas.filter((c) => c.type.kind !== "table");
        return (
          <div className="flex flex-col gap-3">
            <div className="flex items-center gap-2">
              <span className="text-mono text-[var(--color-text-secondary)]">{`[${schema.key}]`}</span>
            </div>
            {scalarLeaves.map((leaf) => (
              <SchemaFieldRenderer
                key={leaf.path.join(".")}
                schema={leaf}
                showAll={showAll}
                getTableChildSchemas={getTableChildSchemas}
                getArrayEntrySchemas={getArrayEntrySchemas}
                getValidator={getValidator}
                onChange={onChange}
                onAddArrayEntry={onAddArrayEntry}
                onRemoveArrayEntry={onRemoveArrayEntry}
                disabled={disabled}
              />
            ))}
            <TabsInline
              tabs={tabs}
              ariaLabel={schema.key}
              idPrefix={schema.path.join("-")}
            />
          </div>
        );
      }

      // Inline section heading (1 or 0 sub-sections — heading + render all children flat)
      return (
        <div className="flex flex-col gap-3">
          <div className="flex items-center gap-2 pt-2">
            <span className="text-mono text-[var(--color-text-secondary)]">{`[${schema.key}]`}</span>
          </div>
          {childSchemas.map((childSchema) => (
            <SchemaFieldRenderer
              key={childSchema.path.join(".")}
              schema={childSchema}
              showAll={showAll}
              getTableChildSchemas={getTableChildSchemas}
              getArrayEntrySchemas={getArrayEntrySchemas}
              getValidator={getValidator}
              onChange={onChange}
              onAddArrayEntry={onAddArrayEntry}
              onRemoveArrayEntry={onRemoveArrayEntry}
              disabled={disabled}
            />
          ))}
        </div>
      );
    }

    case "unknown":
      return (
        <RawUnknownField
          schema={schema}
          onChange={(path, value) => onChange(path, value)}
          disabled={disabled}
        />
      );

    default:
      return null;
  }
}
