LangString addOrReinstall ${LANG_ENGLISH} "Reinstall components"
LangString alreadyInstalled ${LANG_ENGLISH} "Already Installed"
LangString alreadyInstalledLong ${LANG_ENGLISH} "${PRODUCTNAME} ${VERSION} is already installed. Select the operation you want to perform and click Next to continue."
LangString appRunning ${LANG_ENGLISH} "{{product_name}} is running! Please close it first and try again."
LangString appRunningOkKill ${LANG_ENGLISH} "{{product_name}} is running!$\nClick OK to close it"
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Select the maintenance option to perform."
LangString choowHowToInstall ${LANG_ENGLISH} "Choose how you want to install ${PRODUCTNAME}."
LangString createDesktop ${LANG_ENGLISH} "Create a desktop shortcut"
LangString dontUninstall ${LANG_ENGLISH} "Don't uninstall"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "Don't uninstall (Downgrading without uninstall is not allowed)"
LangString failedToKillApp ${LANG_ENGLISH} "Failed to kill {{product_name}}. Please close it first and try again"
LangString installingWebview2 ${LANG_ENGLISH} "Installing WebView2..."
LangString legacyAppReleased ${LANG_ENGLISH} "The program's files have been released."
LangString legacyAppStillLocked ${LANG_ENGLISH} "The program's file is still in use — the installer may ask you to retry."
LangString legacyCoreNoRecord ${LANG_ENGLISH} "There is no record of a running VPN core — nothing to stop."
LangString legacyCoreNotStopped ${LANG_ENGLISH} "A VPN core is running that this installation's record does not name — it was not stopped."
LangString legacyCoreRecordStale ${LANG_ENGLISH} "The VPN core record is stale: that process no longer exists."
LangString legacyCoreRecordUnusable ${LANG_ENGLISH} "The VPN core record cannot be read — there is nothing to stop by it."
LangString legacyCoreStopped ${LANG_ENGLISH} "The VPN core has been stopped."
LangString legacyDataKept ${LANG_ENGLISH} "Your data stays where it is: servers, passwords, known hosts, routing rules and the built-in browser profile."
LangString legacyInstallFound ${LANG_ENGLISH} "Found a previous version of the program in:"
LangString legacyRemoveFailed ${LANG_ENGLISH} "Could not be removed (possibly in use by another program):"
LangString legacyRemoveOnReboot ${LANG_ENGLISH} "Will be removed after a restart:"
LangString legacyRemoving ${LANG_ENGLISH} "Removing:"
LangString legacyStillRunning ${LANG_ENGLISH} "The program is still running — some of the previous files may remain."
LangString legacyStoppingApp ${LANG_ENGLISH} "Closing the running program…"
LangString legacyStoppingCore ${LANG_ENGLISH} "Stopping the VPN core…"
LangString newerVersionInstalled ${LANG_ENGLISH} "A newer version of ${PRODUCTNAME} is already installed! It is not recommended that you install an older version. If you really want to install this older version, it is better to uninstall the current version first. Select the operation you want to perform and click Next to continue."
LangString older ${LANG_ENGLISH} "older"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "An $R4 version of ${PRODUCTNAME} is installed on your system. It is recommended that you uninstall the current version before installing. Select the operation you want to perform and click Next to continue."
LangString silentDowngrades ${LANG_ENGLISH} "Downgrades can not be done silently, please use the installer.$\n"
LangString unableToUninstall ${LANG_ENGLISH} "Unable to uninstall!"
LangString uninstallApp ${LANG_ENGLISH} "Uninstall ${PRODUCTNAME}"
LangString uninstallAutostartTask ${LANG_ENGLISH} "Removing the Windows autostart task..."
LangString uninstallAutostartTaskRemoved ${LANG_ENGLISH} "The Windows autostart task has been removed."
LangString uninstallAutostartTaskAbsent ${LANG_ENGLISH} "There was no Windows autostart task — nothing to remove."
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Reinstall"
LangString unknown ${LANG_ENGLISH} "unknown"
LangString webview2AbortError ${LANG_ENGLISH} "Failed to install WebView2! The app can't run without it. Try restarting the installer."
LangString webview2DownloadError ${LANG_ENGLISH} "Error: Downloading WebView2 Failed - $0"
LangString webview2DownloadSuccess ${LANG_ENGLISH} "WebView2 bootstrapper downloaded successfully"
LangString webview2Downloading ${LANG_ENGLISH} "Downloading WebView2..."
LangString webview2InstallError ${LANG_ENGLISH} "Error: Installing WebView2 failed with exit code $1"
LangString webview2InstallSuccess ${LANG_ENGLISH} "WebView2 installed successfully"
LangString deleteAppData ${LANG_ENGLISH} "Delete everything: servers, passwords, settings. Cannot be undone"
LangString eraseDataRootResolved ${LANG_ENGLISH} "Removing the data folder of this installation:"
LangString eraseDataRootRemoved ${LANG_ENGLISH} "The data folder has been removed."
LangString eraseDataRootPartial ${LANG_ENGLISH} "Some files could not be removed (possibly in use by another program):"
LangString uninstallSchemeKeysKept ${LANG_ENGLISH} "The trusttunnel:// and tt:// links were kept: TrustTunnel Client Light is installed on this computer and uses them."
LangString eraseNoInteractiveDesktop ${LANG_ENGLISH} "Data folder not determined: this uninstall is running with nobody at the keyboard."
LangString eraseNoRecord ${LANG_ENGLISH} "Data folder not determined: the program was never started after it was installed."
LangString eraseRefusedPath ${LANG_ENGLISH} "Data folder not determined: the note about it did not pass validation."
LangString eraseOtherProfile ${LANG_ENGLISH} "Data folder not determined: the note points at a different Windows account."
LangString installRefreshingIconCache ${LANG_ENGLISH} "Refreshing icon cache..."
LangString uninstallDataKept ${LANG_ENGLISH} "Keeping user data"
LangString uninstallCleaningRegistry ${LANG_ENGLISH} "Cleaning registry entries..."
LangString uninstallRemovingUpdateFiles ${LANG_ENGLISH} "Removing temporary update files..."
