LangString addOrReinstall ${LANG_RUSSIAN} "Переустановить компоненты"
LangString alreadyInstalled ${LANG_RUSSIAN} "Уже установлено"
LangString alreadyInstalledLong ${LANG_RUSSIAN} "${PRODUCTNAME} ${VERSION} уже установлен. Выберите действие, которое вы хотите выполнить и нажмите Далее для продолжения."
LangString appRunning ${LANG_RUSSIAN} "{{product_name}} запущен! Пожалуйста, закройте приложение и попробуйте еще раз."
LangString appRunningOkKill ${LANG_RUSSIAN} "{{product_name}} запущен!$\nНажмите OK чтобы закрыть приложение"
LangString chooseMaintenanceOption ${LANG_RUSSIAN} "Выберите действие, которое вы хотите выполнить."
LangString choowHowToInstall ${LANG_RUSSIAN} "Выберите, как вы хотите установить ${PRODUCTNAME}."
LangString createDesktop ${LANG_RUSSIAN} "Добавить ярлык на рабочий стол"
LangString dontUninstall ${LANG_RUSSIAN} "Не удалять"
LangString dontUninstallDowngrade ${LANG_RUSSIAN} "Не удалять (Установка более ранних версий без удаления невозможна)"
LangString failedToKillApp ${LANG_RUSSIAN} "Не удалось закрыть {{product_name}}. Пожалуйста, закройте приложение и попробуйте еще раз"
LangString installingWebview2 ${LANG_RUSSIAN} "Установка WebView2..."
LangString legacyAppReleased ${LANG_RUSSIAN} "Файлы программы освободились."
LangString legacyAppStillLocked ${LANG_RUSSIAN} "Файл программы всё ещё занят — установщик может попросить повторить."
LangString legacyCoreNoRecord ${LANG_RUSSIAN} "Записи о запущенном VPN-ядре нет — останавливать нечего."
LangString legacyCoreNotStopped ${LANG_RUSSIAN} "Найдено VPN-ядро, не совпадающее с записью этой установки — оно не остановлено."
LangString legacyCoreRecordStale ${LANG_RUSSIAN} "Запись о VPN-ядре устарела: такого процесса уже нет."
LangString legacyCoreRecordUnusable ${LANG_RUSSIAN} "Запись о VPN-ядре не читается — останавливать по ней нечего."
LangString legacyCoreStopped ${LANG_RUSSIAN} "VPN-ядро остановлено."
LangString legacyDataKept ${LANG_RUSSIAN} "Ваши данные остаются на месте: серверы, пароли, известные хосты, правила маршрутизации и профиль встроенного браузера."
LangString legacyInstallFound ${LANG_RUSSIAN} "Найдена прошлая версия программы в папке:"
LangString legacyRemoveFailed ${LANG_RUSSIAN} "Не удалось удалить (возможно, занято другой программой):"
LangString legacyRemoveOnReboot ${LANG_RUSSIAN} "Будет удалено после перезагрузки:"
LangString legacyRemoving ${LANG_RUSSIAN} "Удаляется:"
LangString legacyStillRunning ${LANG_RUSSIAN} "Программа всё ещё запущена — часть прошлых файлов может остаться."
LangString legacyStoppingApp ${LANG_RUSSIAN} "Закрываем запущенную программу…"
LangString legacyStoppingCore ${LANG_RUSSIAN} "Останавливаем VPN-ядро…"
LangString newerVersionInstalled ${LANG_RUSSIAN} "Более новая версия ${PRODUCTNAME} уже установлена! Не рекомендуется устанавливать более раннюю версию. Если вы действительно хотите установить эту версию, рекомендуется сначала удалить текущую. Выберите действие, которое вы хотите выполнить и нажмите Далее для продолжения."
LangString older ${LANG_RUSSIAN} "Более ранняя"
LangString olderOrUnknownVersionInstalled ${LANG_RUSSIAN} "$R4 версия ${PRODUCTNAME} уже установлена в вашей системе. Рекомендуется удалить текущую версию перед установкой. Выберите действие, которое вы хотите выполнить и нажмите Далее для продолжения."
LangString silentDowngrades ${LANG_RUSSIAN} "Установка более ранних версий в фоне невозможна, используйте установщик.$\n"
LangString unableToUninstall ${LANG_RUSSIAN} "Не удалось удалить!"
LangString uninstallApp ${LANG_RUSSIAN} "Удалить ${PRODUCTNAME}"
LangString uninstallAutostartTask ${LANG_RUSSIAN} "Удаление задачи автозапуска Windows..."
LangString uninstallAutostartTaskRemoved ${LANG_RUSSIAN} "Задача автозапуска Windows удалена."
LangString uninstallAutostartTaskAbsent ${LANG_RUSSIAN} "Задачи автозапуска Windows не было — удалять нечего."
LangString uninstallBeforeInstalling ${LANG_RUSSIAN} "Переустановить"
LangString unknown ${LANG_RUSSIAN} "Неизвестная"
LangString webview2AbortError ${LANG_RUSSIAN} "Не удалось установить WebView2! Приложение не может работать без него. Попробуйте перезапустить установщик."
LangString webview2DownloadError ${LANG_RUSSIAN} "Ошибка: Не удалось загрузить WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_RUSSIAN} "WebView2 успешно загружен"
LangString webview2Downloading ${LANG_RUSSIAN} "Загрузка WebView2..."
LangString webview2InstallError ${LANG_RUSSIAN} "Ошибка: Не удалось установить WebView2, код выхода: $1"
LangString webview2InstallSuccess ${LANG_RUSSIAN} "WebView2 успешно установлен"
LangString deleteAppData ${LANG_RUSSIAN} "Удалить полностью: серверы, пароли, настройки. Отменить нельзя"
LangString eraseDataRootResolved ${LANG_RUSSIAN} "Удаляется папка с данными этой установки:"
LangString eraseDataRootRemoved ${LANG_RUSSIAN} "Папка с данными удалена."
LangString eraseDataRootPartial ${LANG_RUSSIAN} "Часть файлов удалить не удалось (возможно, заняты другой программой):"
LangString uninstallSchemeKeysKept ${LANG_RUSSIAN} "Ссылки trusttunnel:// и tt:// оставлены: ими пользуется установленная на этом компьютере TrustTunnel Client Light."
LangString eraseNoInteractiveDesktop ${LANG_RUSSIAN} "Папка с данными не определена: удаление идёт без человека за компьютером."
LangString eraseNoRecord ${LANG_RUSSIAN} "Папка с данными не определена: программа ни разу не запускалась после установки."
LangString eraseRefusedPath ${LANG_RUSSIAN} "Папка с данными не определена: запись о ней не прошла проверку."
LangString eraseOtherProfile ${LANG_RUSSIAN} "Папка с данными не определена: запись указывает на другую учётную запись Windows."
LangString installRefreshingIconCache ${LANG_RUSSIAN} "Обновление кэша значков..."
LangString uninstallDataKept ${LANG_RUSSIAN} "Данные пользователя сохраняются"
LangString uninstallCleaningRegistry ${LANG_RUSSIAN} "Очистка записей в реестре..."
LangString uninstallRemovingUpdateFiles ${LANG_RUSSIAN} "Удаление временных файлов обновления..."
